version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind :8000 stripeapi.wsgi:application
    ports:
      - 8000:8000
    env_file:
      - /stripeapi/.env